---
#
#

- hosts: Controller
  remote_user: "{{ host_remote_user|default('heat-admin') }}"
  gather_facts: false
  vars:
    ansible_become: true
    greenlet_pool_size: 100
    max_overflow: 100
  roles:
  - nova-db
