- hosts: Controller
  remote_user: "{{ host_remote_user|default('heat-admin') }}"
  gather_facts: false
  vars:
    ansible_become: true
    driver: neutron.agent.linux.openvswitch_firewall:OVSFirewallDriver
  roles:
  - neutron-firewall

- hosts: Compute
  remote_user: "{{ host_remote_user|default('heat-admin') }}"
  gather_facts: false
  vars:
    ansible_become: true
    driver: neutron.agent.linux.openvswitch_firewall:OVSFirewallDriver
  roles:
  -  neutron-firewall


